
'use strict';
/**
 * ADMIN USER STATUS
 */
let ADMIN_USER_STATUS_ACTIVE = 1 ;
let ADMIN_USER_STATUS_NOT_ACTIVE = 0;

/**
 * USER STATUS
 */
let USER_STATUS_ACTIVE = 1 ;
let USER_STATUS_NOT_ACTIVE = 0;

/**
 * CarStorageRel STATUS
 */
let REL_STATUS_OUT = 2 ;
let REL_STATUS_MOVE = 1;

/**
 * REL ACTIVE STATUS
 */
let REL_STATUS_ACTIVE = 1 ;
let REL_STATUS_NOT_ACTIVE = 0;

module.exports = {
    USER_STATUS_ACTIVE,
    USER_STATUS_NOT_ACTIVE,
    ADMIN_USER_STATUS_ACTIVE,
    ADMIN_USER_STATUS_NOT_ACTIVE,
    REL_STATUS_OUT : REL_STATUS_OUT,
    REL_STATUS_MOVE : REL_STATUS_MOVE,
    REL_STATUS_ACTIVE : REL_STATUS_ACTIVE,
    REL_STATUS_NOT_ACTIVE : REL_STATUS_NOT_ACTIVE,
}